services:
  postgres:
    image: postgres:15
    container_name: task_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: task_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ broker
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      
  taskmicroservice:
    build:
      context: .
      dockerfile: ./TaskService/Dockerfile
    container_name: task_service
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=tasks_db;Username=postgres;Password=postgres"
    ports:
      - "5000:8080"
      
  monitormicroservice:
    build:
      context: .
      dockerfile: ./MonitorService/Dockerfile
    container_name: monitor_service
    restart: always
    depends_on:
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
    - taskmicroservice

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      
      
volumes:
  postgres_data:
  rabbitmq_data:
